import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Main from './main';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  ...pageProps
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id='fb-root'></div>
        <Script
          async
          defer
          crossOrigin='anonymous'
          src='https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v22.0&appId=212321750987465'
          strategy='lazyOnload' // Recommended strategy for non-critical scripts
        />
        <Script
          src='https://cdn.cloud.caster.fm//widgets/embed.js'
          strategy='lazyOnload'
        />
        <Main {...pageProps}>{children}</Main>
      </body>
    </html>
  );
}
